# Generated by Django 5.2.7 on 2025-10-09 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizador",
            ),
        ),
        migrations.AddField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="hassubs",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="hassubs",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_asistiendo",
                through="events.HasSubs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asistentes",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hassubs", unique_together={("username", "name")},
        ),
    ]
